[package]
name = "chip8"
version = "0.1.0"
authors = ["Ilay Rosenberg <ilayrosenberg@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3.1"
num = "0.2.0"
rand = "0.6.5"
sdl2 = "0.32.1"
bitvec = "0.10.0"
rodio = "0.8.1"
piston = "0.42.0"
piston_window = "0.89.0"